# This workflow publishes m30pm build artifacts as tarballs

name: Publish build artifacts as tarballs

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
    branches-ignore: [ main ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install oclif CLI
        run: npm install -g oclif

      - name: Install m30pm dependencies
        run: npm install

      - name: Build m30pm
        run: npm run buildAll

      - name: Package build artifacts as tarballs (for linux-x64)
        run: oclif pack tarballs --targets linux-x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: m30pm-tarballs
          path: dist/m30pm-v*

